call plug#begin()
Plug 'tpope/vim-sensible'
Plug 'nanotech/jellybeans.vim'
Plug 'LaTeX-Box-Team/LaTeX-Box'
call plug#end()
color jellybeans
set number
set shiftwidth=4
set tabstop=4
colorscheme jellybeans
